In [ ]:
def SimCLR_loss(feats,temperature):
    cos_sim = nn.functional.cosine_similarity(feats[:, None, :], feats[None, :, :], dim=-1)
    # Mask out cosine similarity to itself
    self_mask = torch.eye(cos_sim.shape[0], dtype=torch.bool, device=cos_sim.device)
    cos_sim.masked_fill_(self_mask, -9e15)
    # Find positive example -> batch_size//2 away from the original example
    pos_mask = self_mask.roll(shifts=cos_sim.shape[0]//2, dims=0)
    cos_sim = cos_sim / temperature
    nll = -cos_sim[pos_mask] + torch.logsumexp(cos_sim, dim=-1)
    nll = nll.mean()

    return nll

In [ ]:
import torch
import torch.nn as nn

In [ ]:
feat = torch.rand((32.96))

TypeError: rand(): argument 'size' (position 1) must be tuple of ints, but found element of type float at pos 0

In [ ]:
feat = torch.rand((32,96))

In [ ]:
def SimCLR_loss(feats,temperature):
    cos_sim = nn.functional.cosine_similarity(feats[:, None, :], feats[None, :, :], dim=-1)
    print(cos_sim)
    # Mask out cosine similarity to itself
    self_mask = torch.eye(cos_sim.shape[0], dtype=torch.bool, device=cos_sim.device)
    print('\n')

    print(self_mask)
    cos_sim.masked_fill_(self_mask, -9e15)
    print('\n')

    print(cos_sim)
    # Find positive example -> batch_size//2 away from the original example
    pos_mask = self_mask.roll(shifts=cos_sim.shape[0]//2, dims=0)
    print('\n')
    print(pos_mask)
    cos_sim = cos_sim / temperature
    nll = -cos_sim[pos_mask] + torch.logsumexp(cos_sim, dim=-1)
    nll = nll.mean()

    return nll

In [ ]:
SimCLR_loss(feat,0.7)

tensor([[1.0000, 0.7207, 0.7598,  ..., 0.7758, 0.7156, 0.6967],
        [0.7207, 1.0000, 0.7486,  ..., 0.7414, 0.7738, 0.7125],
        [0.7598, 0.7486, 1.0000,  ..., 0.8220, 0.8346, 0.7687],
        ...,
        [0.7758, 0.7414, 0.8220,  ..., 1.0000, 0.7670, 0.7855],
        [0.7156, 0.7738, 0.8346,  ..., 0.7670, 1.0000, 0.7192],
        [0.6967, 0.7125, 0.7687,  ..., 0.7855, 0.7192, 1.0000]])


tensor([[ True, False, False,  ..., False, False, False],
        [False,  True, False,  ..., False, False, False],
        [False, False,  True,  ..., False, False, False],
        ...,
        [False, False, False,  ...,  True, False, False],
        [False, False, False,  ..., False,  True, False],
        [False, False, False,  ..., False, False,  True]])


tensor([[-9.0000e+15,  7.2065e-01,  7.5981e-01,  ...,  7.7585e-01,
          7.1564e-01,  6.9666e-01],
        [ 7.2065e-01, -9.0000e+15,  7.4861e-01,  ...,  7.4144e-01,
          7.7376e-01,  7.1249e-01],
        [ 7.5981e-01,  7.4861e

tensor(3.4488)

In [ ]:
feat = torch.rand((2,5))

In [ ]:
SimCLR_loss(feat,0.07)

tensor([[1.0000, 0.5328],
        [0.5328, 1.0000]])


tensor([[ True, False],
        [False,  True]])


tensor([[-9.0000e+15,  5.3276e-01],
        [ 5.3276e-01, -9.0000e+15]])


tensor([[False,  True],
        [ True, False]])


tensor(0.)

In [ ]:
feat = torch.rand((4,4))

In [ ]:
SimCLR_loss(feat,0.07)

tensor([[1.0000, 0.9654, 0.6516, 0.9185],
        [0.9654, 1.0000, 0.7582, 0.8918],
        [0.6516, 0.7582, 1.0000, 0.5831],
        [0.9185, 0.8918, 0.5831, 1.0000]])


tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])


tensor([[-9.0000e+15,  9.6542e-01,  6.5160e-01,  9.1846e-01],
        [ 9.6542e-01, -9.0000e+15,  7.5822e-01,  8.9181e-01],
        [ 6.5160e-01,  7.5822e-01, -9.0000e+15,  5.8305e-01],
        [ 9.1846e-01,  8.9181e-01,  5.8305e-01, -9.0000e+15]])


tensor([[False, False,  True, False],
        [False, False, False,  True],
        [ True, False, False, False],
        [False,  True, False, False]])


tensor(2.2461)

In [ ]:
def SimCLR_loss(feats,temperature):
    cos_sim = nn.functional.cosine_similarity(feats[:, None, :], feats[None, :, :], dim=-1)
    print(cos_sim)
    # Mask out cosine similarity to itself
    self_mask = torch.eye(cos_sim.shape[0], dtype=torch.bool, device=cos_sim.device)
    print('\n')

    print(self_mask)
    cos_sim.masked_fill_(self_mask, -9e15)
    print('\n')

    print(cos_sim)
    # Find positive example -> batch_size//2 away from the original example
    pos_mask = self_mask.roll(shifts=cos_sim.shape[0]//2, dims=0)
    print('\n')
    print(pos_mask)
    print('\n')
    print(torch.logsumexp(cos_sim, dim=-1))
    cos_sim = cos_sim / temperature
    nll = -cos_sim[pos_mask] + torch.logsumexp(cos_sim, dim=-1)
    nll = nll.mean()

    return nll

In [ ]:
SimCLR_loss(feat,0.07)

tensor([[1.0000, 0.9654, 0.6516, 0.9185],
        [0.9654, 1.0000, 0.7582, 0.8918],
        [0.6516, 0.7582, 1.0000, 0.5831],
        [0.9185, 0.8918, 0.5831, 1.0000]])


tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])


tensor([[-9.0000e+15,  9.6542e-01,  6.5160e-01,  9.1846e-01],
        [ 9.6542e-01, -9.0000e+15,  7.5822e-01,  8.9181e-01],
        [ 6.5160e-01,  7.5822e-01, -9.0000e+15,  5.8305e-01],
        [ 9.1846e-01,  8.9181e-01,  5.8305e-01, -9.0000e+15]])


tensor([[False, False,  True, False],
        [False, False, False,  True],
        [ True, False, False, False],
        [False,  True, False, False]])


tensor([1.9530, 1.9741, 1.7655, 1.9075])


tensor(2.2461)

In [ ]:
torch.exp(-9e15)

TypeError: exp(): argument 'input' (position 1) must be Tensor, not float

In [ ]:
torch.exp(torch.tensor(-9e15))

tensor(0.)

In [ ]:
torch.exp(torch.tensor(0))

tensor(1.)