In [ ]:
from PIL import Image
from torchvision.transforms import ToTensor
image = Image.open(r'C:\Users\k54739\OneDrive\Thesis\.tiff_experiment_unsupervised_data\combined\1.tiff')
image = ToTensor()(image)
print(image)

In [ ]:
from PIL import Image
import os

# Correct file path with image name
file_path = r'C:\Users\k54739\OneDrive\Thesis\.tiff_experiment_unsupervised_data\combined\1.tiff'

# Ensure the path points to an existing file
if os.path.isfile(file_path):
    image = Image.open(file_path)
    
    # Print image mode (e.g., "L" for 8-bit grayscale, "I;16" for 16-bit grayscale, "RGB" for RGB)
    print(f"Image mode: {image.mode}")
    
    # If the image is in grayscale mode, check the bit depth
    if image.mode == "I;16":
        print("The image is a 16-bit grayscale image.")
    elif image.mode == "L":
        print("The image is an 8-bit grayscale image.")
    elif image.mode == "RGB":
        print("The image is an RGB image.")
    else:
        print(f"The image has an unsupported mode: {image.mode}")
    
    # Additional image properties
    print(f"Image size: {image.size}")
    print(f"Image format: {image.format}")
else:
    print(f"File not found: {file_path}")


In [13]:
from tifffile import imread
from torchvision.transforms import ToTensor
import torch


In [14]:
image= imread((r'C:\Users\k54739\OneDrive\Thesis\.tiff_experiment_unsupervised_data\combined\1.tiff'))
image = ToTensor()(image)

In [15]:
print(image)

tensor([[[30519, 29847, 29351,  ..., 29447, 30071, 29399],
         [30967, 29607, 30119,  ..., 30647, 30903, 29479],
         [29351, 30455, 30215,  ..., 31063, 30199, 30711]],

        [[30535, 29975, 29911,  ..., 31175, 29991, 30119],
         [29431, 30439, 29271,  ..., 30023, 29911, 29767],
         [29863, 30807, 29543,  ..., 30727, 30487, 30759]],

        [[30151, 30311, 30439,  ..., 30615, 30167, 30839],
         [30199, 30183, 30039,  ..., 30103, 29831, 30311],
         [30503, 30823, 31255,  ..., 31335, 30263, 29991]],

        ...,

        [[31479, 31239, 30359,  ..., 30167, 30887, 29943],
         [30631, 31383, 29847,  ..., 30631, 30119, 30151],
         [31543, 30807, 30407,  ..., 30615, 30663, 30519]],

        [[31095, 31063, 30247,  ..., 30727, 29271, 30711],
         [31495, 30695, 30871,  ..., 29895, 30087, 29671],
         [31639, 30503, 30567,  ..., 29687, 30231, 30135]],

        [[30871, 30759, 30135,  ..., 30103, 30647, 30583],
         [30503, 29879, 29751,  

In [17]:
image_tensor = image.to(torch.float32)

# Print the maximum pixel value
max_pixel_value = torch.max(image_tensor)
print(f"Maximum pixel value: {max_pixel_value.item()}")

Maximum pixel value: 39417.0


In [23]:
import cv2

image = cv2.imread(r'C:\Users\k54739\OneDrive\Thesis\.tiff_experiment_unsupervised_data\combined\1.tiff',cv2.IMREAD_UNCHANGED)
print(image)


[[30519 30535 30151 ... 31479 31095 30871]
 [29847 29975 30311 ... 31239 31063 30759]
 [29351 29911 30439 ... 30359 30247 30135]
 ...
 [29447 31175 30615 ... 30167 30727 30103]
 [30071 29991 30167 ... 30887 29271 30647]
 [29399 30119 30839 ... 29943 30711 30583]]


In [ ]:
tf_tensor = tf.convert_to_tensor(image, dtype=float32)